Add StaticTest.vm
wildmaples/jack-virtual-machine pull request #13
Opened 2021-09-14 23:15 UTC by wildmaples

The last `.vm` file to implement in our chapter.

2021-09-15 12:12 UTC, tomstuart requested changes
Sorry, this isn’t right! Confusingly it does make the `StaticTest.tst` test pass, so I understand why you did it, but it doesn’t meet the specification of the `static` segment at the top of page 143:

> According to the Hack machine language specification, when a new symbol is encountered for the first time in an assembly program, the assembler allocates a new RAM address to it, starting at address 16. This convention can be exploited to represent each static variable number `j` in a VM file `f` as the assembly language symbol `f.j`. For example, suppose that the file `Xxx.vm` contains the command `push static 3`. This command can be translated to the Hack assembly commands `@Xxx.3` and `D=M`, followed by additional assembly code that pushes `D`’s value to the stack. This implementation of the `static` segment is somewhat tricky, but it works.

“Somewhat tricky” indeed. The idea is to depend upon the [existing behaviour](https://github.com/wildmaples/ruby-hack-assembler/blob/main/test/unit/assembler_test.rb#L59-L63) of the Hack assembler, which assigns user-defined “variable symbols” to distinct addresses in the symbol table, [starting at address 16](https://github.com/wildmaples/ruby-hack-assembler/blob/main/lib/assembler.rb#L11) and [auto-incrementing the address](https://github.com/wildmaples/ruby-hack-assembler/blob/main/lib/assembler.rb#L72-L73) each time a new symbol is added.

Concretely, the A-command that you generate from `pop static 8` to load the destination address into the A register should be `@StaticTest.8`, not `@24`, so that the assembler gets to decide which address to assign to the new `StaticTest.8` symbol. The reason `StaticTest.tst` passes regardless is that [`StaticTest.cmp`](https://github.com/wildmaples/nand2tetris/blob/master/projects/07/MemoryAccess/StaticTest/StaticTest.cmp) doesn’t actually check which addresses you used, only that the correct value ends up on the top of the stack. So the fact that you’re using addresses 24, 19 and 17 instead of letting the assembler decide where to store `@StaticTest.8`, `@StaticTest.3` and `@StaticTest.1` (i.e. addresses 16, 17 and 18) isn’t visible to the test.

So why does it even matter? Because, although we haven’t tried it yet, the VM translator has to support translating multiple files at once (e.g. for [`FibonacciElement`](https://github.com/wildmaples/nand2tetris/tree/master/projects/08/FunctionCalls/FibonacciElement) in the next chapter) into a single `.asm` file. In theory we already learned about this on page 143:

> The VM translator should accept a single command line parameter, as follows: 
>
> `prompt> VMtranslator source`
>
>
> Where _source_ is either a file name of the form `Xxx.vm` (the extension is mandatory) or a directory name containing one or more `.vm` files (in which case there is no extension). The result of the translation is always a single assembly language file named `Xxx.asm`, created in the same directory as the input `Xxx`. The translated code must conform to the standard VM mapping on the Hack platform. 

And on page 146:

> If the program’s argument is a directory name rather than a file name, the main program should process all the `.vm` files in this directory. In doing so, it should use a separate `Parser` for handling each input file and a single `CodeWriter` for handling the output. 

In practice we haven’t had to deal with any of this because we haven’t needed to translate multiple VM files yet. But when we do, it’s important that `Foo.vm` can read and write to `static 8` without interfering with `Bar.vm`’s `static 8`. If we always translate `static 8` into address 24 then those two VM files will be fighting over the use of the same memory location; the solution is to translate one into `@Foo.8` and the other into `@Bar.8`, so that the assembler will take care of assigning those variable symbols to distinct addresses (e.g. 16 and 17) that don’t clash.

2021-09-15 12:12 UTC, tomstuart commented on test/fixtures/StaticTest.asm
> +@24
```suggestion
@StaticTest.8
```

2021-09-15 12:12 UTC, tomstuart commented on test/fixtures/StaticTest.asm
> +@24
```suggestion
@StaticTest.8
```

2021-09-15 12:12 UTC, tomstuart commented on test/fixtures/StaticTest.asm
> +@19
```suggestion
@StaticTest.3
```

2021-09-15 12:12 UTC, tomstuart commented on test/fixtures/StaticTest.asm
> +@19
```suggestion
@StaticTest.3
```

2021-09-15 12:12 UTC, tomstuart commented on test/fixtures/StaticTest.asm
> +@17
```suggestion
@StaticTest.1
```

2021-09-15 12:12 UTC, tomstuart commented on test/fixtures/StaticTest.asm
> +@17
```suggestion
@StaticTest.1
```

2021-09-24 16:08 UTC, wildmaples commented on bin/vm-translator
> +  raise ArgumentError.new("We can only translate a single .vm file at a time")
https://github.com/wildmaples/jack-virtual-machine/issues/15

2021-09-24 16:09 UTC, tomstuart approved these changes
This looks good, well done! I think we’ll want to revisit the `VMTranslator` setup once we need to translate multiple files at once, but we’re not there yet, so this is good right now. 🎉

2021-09-24 16:57 UTC, merged